### PR TITLE
[netcore][17.multilingual-bot] Fix typos and improve formatting

### PR DESCRIPTION
**Pull request by VictorGrycuk**
## Proposed Changes
Fix several typos in sample # 17 and minor text format fixes
## Testing
Code behavior was not modified.

### CODE REVIEW

**Review by joseques — APPROVED** [review]
:shipit: 👕

**Review by dfavretto — CHANGES_REQUESTED** [review]
[line 5](https://github.com/southworkscom/BotBuilder-Samples/pull/81/files#diff-b11a27c32b92f2c9535fa4c7d052527aL5) change `langugage` for `language`
[line 17](https://github.com/southworkscom/BotBuilder-Samples/pull/81/files#diff-b11a27c32b92f2c9535fa4c7d052527aL17) change `traslate` for `translate`
[line 18](https://github.com/southworkscom/BotBuilder-Samples/pull/81/files#diff-b11a27c32b92f2c9535fa4c7d052527aL18) change `ellaborated` for `elaborated`

**Comment by VictorGrycuk** [comment]
@dfavretto Fixed

**Review by dfavretto — APPROVED** [review]

**Comment by dfavretto** [comment]
Closed due to Microsoft#701

**Pull request closed without merging**
