### PR TITLE
[netcore][03.welcome-user] Fix typos and improvements

### PR DESCRIPTION
**Pull request by VictorGrycuk**
## Proposed Changes
Fix several typos in sample # 03 `welcome-user`
## Testing
Sample documentation and code should not have typos

### CODE REVIEW

**Review by dfavretto — APPROVED** [review]
LGTM :shipit:

**Review by joseques — APPROVED** [review]
:shipit:

**Review by dfavretto — APPROVED** [review]
LGTM

**Comment by VictorGrycuk** [comment]
Replaced https://github.com/Microsoft/BotBuilder-Samples/pull/619

**Pull request closed without merging**
