### PR TITLE
[MVC] Move 'BookingDetails' to 'Models' folder in Sample #13 - Basic Bot

### PR DESCRIPTION
**Pull request by VictorGrycuk**
## Proposed Changes
- Create a folder named `Models` to contain the model classes

**Note:** We created this PR against `samples-work-in-progress` because here is where we reviewed the sample. On the other hand, we noticed these changes are also merged in `4.3/js/core` branch.
Let us know if we should rebase this PR.

## Testing
This modification does not change the code logic

### CODE REVIEW

**Review by gasper-az — COMMENTED** [review]
As @JuanAr commented in #181, the base branch should be `samples-work-in-progress`

**Comment by VictorGrycuk** [comment]
@GasparAcevedoZainSouthworks The branch has been rebased and the PR was modified to be against `samples-work-in-progress`. Please review again.

**Review by JuanAr — APPROVED** [review]
LGTM

**Review by ParadoxARG — APPROVED** [review]

**Review by gasper-az — APPROVED** [review]
:shipit:

**Comment by gasper-az** [comment]
Promoted to MS # 1332

**Pull request closed without merging**
