### PR TITLE
[typescript][02.echo with counter] Fixed minor typos for README

### PR DESCRIPTION
**Pull request by joseques**
## Proposed Changes
- Minor changes to typos and minimal structural changes.
- Changed `&` to `&&` since only one ampersand makes the commands run asynchronously thus fail due to `npm start` being executed **before** `npm i` can finish installing the dependencies.

### CODE REVIEW

**Review by VictorGrycuk — APPROVED** [review]
👍

**Review by dfavretto — CHANGES_REQUESTED** [review]
Implement same change as seen in [#66](https://github.com/southworkscom/BotBuilder-Samples/pull/66/files#diff-121cd7b2bed5cb006c98e3741f97a145R26) for `Deploy this bot to Azure`

**Comment by joseques** [comment]
@dfavretto The section has been implemented.

**Comment by dfavretto** [comment]
Closed due to #663

**Pull request closed without merging**
