### PR TITLE
[netcore][01.console-echo] Add missing step and improve format

### PR DESCRIPTION
**Pull request by VictorGrycuk**
## Proposed Changes
- Add missing step to update packages in VS Code.
- Small format improvement
## Testing
Code behavior was not modified.

### CODE REVIEW

**Review by joseques — APPROVED** [review]
👍

**Review by dfavretto — CHANGES_REQUESTED** [review]
Following the [Readme template](https://github.com/Microsoft/BotBuilder-Samples/blob/stgum/csharp_dispatch/SPEC.md#readmemd-template) it would be great if you could add a `Testing the bot using Bot Framework Emulator` section.

**Comment by VictorGrycuk** [comment]
@dfavretto That is not possible since this is a simple console bot, the sample does not contain a `.bot` file.

**Review by dfavretto — APPROVED** [review]
LGTM

**Pull request merged**
