### PR TITLE
[webapi][11.qnamaker] Fix typos 

### PR DESCRIPTION
**Pull request by joseques**
## Proposed Changes
- Minor changes to typos the README.md

### CODE REVIEW

**Review by VictorGrycuk — CHANGES_REQUESTED** [review]
Should both `.bot` be included in the PR?

**Comment by joseques** [comment]
Those were added by mistake. Resolved @VictorGrycuk

**Review by VictorGrycuk — APPROVED** [review]
LGTM!

**Comment by dfavretto** [comment]
Closed due to Microsoft#762

**Pull request closed without merging**
