### PR TITLE
[MVC] Fix typos in Sample #13 - Basic Bot

### PR DESCRIPTION
**Pull request by VictorGrycuk**
## Proposed Changes
- Fix a pair of typos found in the comments

**Note:** We created this PR against `samples-work-in-progress` because here is where we reviewed the sample. On the other hand, we noticed these changes are also merged in `4.3/js/core` branch.
Let us know if we should rebase this PR.

### CODE REVIEW

**Review by ParadoxARG — APPROVED** [review]
:shipit:

**Review by gasper-az — APPROVED** [review]
:shipit:

**Review by JuanAr — APPROVED** [review]
👍

**Comment by JuanAr** [comment]
Wait! The base branch is incorrect! Should be `samples-work-in-progress`.

**Comment by VictorGrycuk** [comment]
@JuanAr Indeed. I used `4.3/js/core` because yesterday the branch for the sample # 13 was merged to this branch. I will rebase the changes.

**Comment by JuanAr** [comment]
Didn't know that! However, isn't it strange that a C# sample is being merged to a `*/js/*` named branch? Maybe they wanted some changes included in the samples branch.
Yes, I would still create the PR against the `samples-work-in-progress` branch.

**Review by ParadoxARG — APPROVED** [review]

**Review by JuanAr — APPROVED** [review]
LGTM

**Comment by VictorGrycuk** [comment]
@JuanAr The branch has been rebased and the PR was modified to be against `samples-work-in-progress`. Please review again.

**Review by gasper-az — APPROVED** [review]
:shipit:

**Comment by gasper-az** [comment]
Promoted to MS # 1331

**Pull request closed without merging**
