### PR TITLE
[webapi][13.basic bot] README structure enhancement and typos fixes

### PR DESCRIPTION
**Pull request by joseques**
## Proposed Changes
- Enhance README structure
- Fix minor typos

### CODE REVIEW

**Comment by VictorGrycuk** [comment]
- Fix typo in [line 112](https://github.com/southworkscom/BotBuilder-Samples/blob/4c44d4b21c1351b03aadfcef00bd8260a0da1b23/samples/csharp_webapi/13.Basic-Bot-Template/Dialogs/Shared/DetectHelpCancelDialog.cs#L112) of `DetectHelpCancelDialog.cs`, `cancelled` for `canceled`
- Fix typo in [line 19](https://github.com/southworkscom/BotBuilder-Samples/blob/4c44d4b21c1351b03aadfcef00bd8260a0da1b23/samples/csharp_webapi/13.Basic-Bot-Template/Dialogs/Shared/RouterDialog.cs#L19) of `RouterDialog.cs`, `inital` for `initial`.
- Fix typo in [line 25](https://github.com/southworkscom/BotBuilder-Samples/blob/4c44d4b21c1351b03aadfcef00bd8260a0da1b23/samples/csharp_webapi/13.Basic-Bot-Template/App_Start/BotConfig.cs#L25) of `BotConfig.cs`, `framwork` for `framework`
- Double espaces in various files

**Review by VictorGrycuk — CHANGES_REQUESTED** [review]
Requested changes, please see comments

**Comment by joseques** [comment]
The changes have been implemented @VictorGrycuk

**Review by VictorGrycuk — APPROVED** [review]
Ship it 👍

**Comment by dfavretto** [comment]
Closed due to Microsoft#784

**Pull request closed without merging**
