### PR TITLE
[#3740] Update dotnet samples to target Net 6 - QnA maker samples

### PR DESCRIPTION
**Pull request by erquirogasw**
Addresses # 3740
#minor

## Description
This PR updates the QnA maker samples to target .NET6

## Specific Changes
- Updated the following samples to target .NET6
  - CustomQABot
  - CustomQABotAllFeatures
  - QnABot
  - QnABotAllFeatures
- README files updated to target .NET6

## Testing
CustomQABot working
image (83)

CustomQABotAllFeatures working
image (84)

QnABot working
image

QnABotAllFeatures working
image (88)

### CODE REVIEW

**Review by sw-joelmut — CHANGES_REQUESTED** [review]
For the qna all features, the readme contains a reference link to the 3.1 version

**Review by sw-joelmut — CHANGES_REQUESTED** [review]
Also the 12.customQABot is missing, i just did a swipe to check all missing bots just in case, this one is missing only

**Comment by erquirogasw** [comment]
> For the qna all features, the readme contains a reference link to the 3.1 version



> Also the 12.customQABot is missing, i just did a swipe to check all missing bots just in case, this one is missing only

Fixed.

**Review by sw-joelmut — APPROVED** [review]

**Review by ceciliaavila — APPROVED** [review]

**Pull request closed without merging**
