### PR TITLE
[netcore][02.echo with counter] Fix typos and update Readme.md

### PR DESCRIPTION
**Pull request by dfavretto**
## Proposed Changes
  - Fix some typos in `Startup.cs` file.
  - Edit some content in the `Readme.md` file.

### CODE REVIEW

**Review by VictorGrycuk — DISMISSED** [review]
- Line 12 of `README.md`, format it as: Run the project (press `F5` key)
- Line 17 of `README.md`, format it as: Type `dotnet run`.
- Line 43 of `README.md`, minor style improvement: set the code block to `bash` language

**Review by joseques — APPROVED** [review]
LGTM

**Review by VictorGrycuk — APPROVED** [review]
LGTM

**Comment by dfavretto** [comment]
Closed due to #672

**Pull request closed without merging**
