### PR TITLE
[nodejs][06.using cards] Fix typos and improve formatting 

### PR DESCRIPTION
**Pull request by joseques**
## Proposed Changes

- Minor changes to typos and minimal structural changes.
- Change the section `Deploy this bot to Azure` linking existing documentation

### CODE REVIEW

**Review by VictorGrycuk — CHANGES_REQUESTED** [review]
[Line 12](https://github.com/southworkscom/BotBuilder-Samples/blob/8f7c0a4402c1cf2035601beb1fdd91bf86217932/samples/javascript_nodejs/06.using-cards/README.md#to-try-this-sample) of readme, format the path in `code style`.

**Comment by joseques** [comment]
Changed paths in `code style` @VictorGrycuk

**Review by VictorGrycuk — APPROVED** [review]
LGTM!

**Review by dfavretto — APPROVED** [review]
LGTM

**Comment by dfavretto** [comment]
Closed due to Microsoft#734

**Pull request closed without merging**
